

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test111
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true
    show-sql: true
    generate-ddl: false
server:
  port: 8081
